/********* DATAS ***********/
export const foodsItem = [{
    id: 1,
    category: "Drinks",
    itemName: "Coke",
    subCategory: "Carbonated Drink",
    sizes: [
        {size: "Regular", price: 25},
    ], 
    imgurl: "assets/images/Drinks/Coke.jpg",
    category: "drinks",
    all: "all",
    description: "Cola is a carbonated soft drink flavored with vanilla, cinnamon, citrus oils and other flavorings.",
    quantity: 1,
}, {
    id: 2,
    category: "Drinks",
    itemName: "Bottled Water",
    subCategory: "Carbonated Drink",
    sizes: [
        {size: "Regular", price: 35},
    ], 
    imgurl: "assets/images/Drinks/Bottled Water.jpg",
    category: "drinks",
    all: "all",
    description: "Water is h2O, a clear, colorless, odorless, tasteless liquid that freezes into ice below 0 degrees centigrade and boils above 100 degrees centigrade.",
    quantity: 1,
}, {
    id: 3,
    category: "Drinks",
    itemName: "Diet Soda",
    subCategory: "Carbonated Drink",
    sizes: [
        {size: "Regular", price: 25},
    ], 
    imgurl: "assets/images/Drinks/Diet Soda.jpg",
    category: "drinks",
    all: "all",
    description: "Lipton Yellow Label is blended from about 20 different teas",
    quantity: 1,
}, {
    id: 4,
    category: "Drinks",
    itemName: "Lipton",
    subCategory: "Carbonated Drink",
    sizes: [
        {size: "Regular", price: 30},
    ], 
    imgurl: "assets/images/Drinks/Lipton.jpg",
    category: "drinks",
    all: "all",
    description: "Lipton Yellow Label is blended from about 20 different teas",
    quantity: 1,
}, {
    id: 5,
    category: "Drinks",
    itemName: "Ice Tea",
    subCategory: "Carbonated Drink",
    sizes: [
        {size: "Regular", price: 55},
    ], 
    imgurl: "assets/images/Drinks/Ice Tea.jpg",
    category: "drinks",
    all: "all",
    description: "It may or may not be sweetened and is also a popular packaged drink. It can be mixed with flavored syrup with multiple common flavors including lemon, raspberry, lime, passion fruit, peach, orange, strawberry, and cherry.",
    quantity: 1,
}, {
    id: 6,
    category: "Drinks",
    itemName: "Double Dutch Shake",
    subCategory: "Shakes",
    sizes: [
        {size: "Regular", price: 85},
    ], 
    imgurl: "assets/images/Drinks/Double Dutch Shake.jpg",
    category: "drinks",
    all: "all",
    description: "Place muffin in blender. Add ice cream and milk. Cover and blend until smooth. Pour into prepared glasses. Top with whipped cream and a candy bar square.",
    quantity: 1,
}, {
    id: 7,
    category: "Drinks",
    itemName: "Black Forest Shake",
    subCategory: "Shakes",
    sizes: [
        {size: "Regular", price: 25},
    ], 
    imgurl: "assets/images/Drinks/Black Forest Shake.jpg",
    category: "drinks",
    all: "all",
    description: "Black Forest is a type of cake that is made from chocolate cake that has layers of cherries and whipped cream sandwiched between the layers.",
    quantity: 1,
}, {
    id: 8,
    category: "Drinks",
    itemName: "Banana Shake",
    subCategory: "Shakes",
    sizes: [
        {size: "Small", price: 69},
        {size: "Medium", price: 80},
        {size: "Large", price: 119},

    ], 
    imgurl: "assets/images/Drinks/SMALL_Banana Shake.jpg",
    category: "drinks",
    all: "all",
    description: "Banana shakes are a versatile drink that can be enjoyed by most people and tailored to support specific health or fitness goals.",
    quantity: 1,
}, {
    id: 11,
    category: "Drinks",
    itemName: "Mango Shake",
    subCategory: "Shakes",
    sizes: [
        {size: "Small", price: 69},
        {size: "Medium", price: 80},
        {size: "Large", price: 119},
    ], 
    imgurl: "assets/images/Drinks/SMALL_Mango Shake.jpg",
    category: "drinks",
    all: "all",
    description: "Mango shake is a refreshing summer drink made with blended Philippine mangoes, evaporated milk and simple syrup.",
    quantity: 1,
}, {
    id: 14,
    category: "Drinks",
    itemName: "Hot Tea Latte",
    subCategory: "Hot Coffee",
    sizes: [
        {size: "Regular", price: 140},
    ], 
    imgurl: "assets/images/Drinks/Hot Tea Latte.jpg",
    category: "drinks",
    all: "all",
    description: "Made with steamed, frothy milk, blended with our rich, freshly ground and brewed espresso.",
    quantity: 1,
}, {
    id: 15,
    category: "Drinks",
    itemName: "Cappuccino",
    subCategory: "Hot Coffee",
    sizes: [
        {size: "Regular", price: 140},
    ], 
    imgurl: "assets/images/Drinks/Cappuccino.jpeg",
    category: "drinks",
    all: "all",
    description: "A cappuccino is the perfect balance of espresso, steamed milk and foam.",
    quantity: 1,
}, {
    id: 16,
    category: "Drinks",
    itemName: "Brewed Coffee",
    subCategory: "Hot Coffee",
    sizes: [
        {size: "Regular", price: 140},
    ], 
    imgurl: "assets/images/Drinks/Brewed Coffee.jpg",
    category: "drinks",
    all: "all",
    description: "Brewed Coffee is a beverage brewed from the roasted and ground seeds of the tropical evergreen coffee plant",
    quantity: 1,
}, {
    id: 17,
    category: "Drinks",
    itemName: "Mocha Iced Coffee",
    subCategory: "Cold Coffee",
    sizes: [
        {size: "Regular", price: 120},
    ], 
    imgurl: "assets/images/Drinks/Mocha Ice Coffee.jpg",
    category: "drinks",
    all: "all",
    description: "An iced mocha is a coffee drink made with espresso, milk and chocolate, served over ice.",
    quantity: 1,
}, {
    id: 18,
    category: "Drinks",
    itemName: "Vanilla Iced Coffee",
    subCategory: "Cold Coffee",
    sizes: [
        {size: "Regular", price: 120},
    ], 
    imgurl: "assets/images/Drinks/Vanilla Ice Coffee.jpg",
    category: "drinks",
    all: "all",
    description: "The decadently creamy flavor medley of milk, sweet vanilla, fresh coffee, and ice simply can not be rivaled.",
    quantity: 1,
}, {
    id: 19,
    category: "Drinks",
    itemName: "Iced Coffee",
    subCategory: "Cold Coffee",
    sizes: [
        {size: "Regular", price: 120},
    ], 
    imgurl: "assets/images/Drinks/Ice Coffee.jpg",
    category: "drinks",
    all: "all",
    description: "Quite simply, an iced coffee is a cold version of your favourite coffee, but it's not simply a coffee that has been left to cool. Like a Small coffee, it's usually a combination of hot espresso and milk.",
    quantity: 1,
}, {
    id: 20,
    category: "Drinks",
    itemName: "Alfonso",
    subCategory: "Beers",
    sizes: [
        {size: "1 Liter", price: 650},
    ], 
    imgurl: "assets/images/Drinks/Alfonso.jpg",
    category: "drinks",
    all: "all",
    description: "Colour: light amber coloured brandy. Odour: It maintains the strength of rich aromas. Taste: It is soft and, though completely dry, has a sense of sweetness on the palate, which is a classic characteristic of \"old cask\" sherry ageing. Refreshing taste",
    quantity: 1,
}, {
    id: 21,
    category: "Drinks",
    itemName: "Red Horse",
    subCategory: "Beers",
    sizes: [
        {size: "1 Liter", price: 120},
        {size: "Bucket", price: 450},
    ], 
    imgurl: "assets/images/Drinks/Red Horse.png",
    category: "drinks",
    all: "all",
    description: "It is deeply hued lager with a distinctive, sweetish taste, balanced by a smooth bitterness. For the man with real strength, inside and out. A strong, high alcohol beer. It is deeply hued lager with a distinctive, sweetish taste, balanced by a smooth bitterness.",
    quantity: 1,
},{
    id: 23,
    category: "Drinks",
    itemName: "San Miguel Light",
    subCategory: "Beers",
    sizes: [
        {size: "Solo", price: 70},
        {size: "Bucket", price: 350},
    ], 
    imgurl: "assets/images/Drinks/SOLO_San Miguel Light.jpg",
    category: "drinks",
    all: "all",
    description: "A light and reduced-calorie lager with an exceptionally smooth and crispy taste. It is less filling and light on the stomach. Perfect for fun, light drinking moments with friends.",
    quantity: 1,
},{
    id: 25,
    category: "Drinks",
    itemName: "Pale Pilsen",
    subCategory: "Beers",
    sizes: [
        {size: "Solo", price: 70},
        {size: "Bucket", price: 350},
    ], 
    imgurl: "assets/images/Drinks/SOLO_Pale Pilsen.png",
    category: "drinks",
    all: "all",
    description: "San Miguel Pale Pilsen is a pale, golden lager with a rich, full-bodied flavour. Its smooth, full-flavored taste complements its pleasant aroma, making it a perfectly balanced beer. It has a unique heritage of bringing people together, nourishing true friendships for over a hundred years.",
    quantity: 1,
},{
    id: 27,
    category: "Foods",
    itemName: "Pork Adobo",
    subCategory: "Main Dish",
    sizes: [
        {size: "Regular", price: 250},
    ], 
    imgurl: "assets/images/MainDish/Pork Adobo.jpg",
    category: "foods",
    all: "all",
    description: "Pork Adobo is a traditional stew originating from the Philippines. This type of Filipino adobo is made with a combination of pork belly, garlic, soy sauce, vinegar, sugar, bay leaves, peppercorns, and salt. The pork is marinated in a combination of garlic and soy sauce, and it's then browned in a pan over high heat.",
    quantity: 1,
}, {
    id: 28,
    category: "Foods",
    itemName: "Pinoy Chicken Curry",
    subCategory: "Main Dish",
    sizes: [
        {size: "Regular", price: 250},
    ], 
    imgurl: "assets/images/MainDish/Pinoy Chicken Curry.jpg",
    category: "foods",
    all: "all",
    description: "A dish composed with a sauce or gravy seasoned with a mixture of ground spices that is thought to have originated in India and has since spread to many regions of the world. The foundation of many Indian curries is a mixture of onion, ginger, and garlic.",
    quantity: 1,
}, {
    id: 29,
    category: "Foods",
    itemName: "Beef Bulalo",
    subCategory: "Main Dish",
    sizes: [
        {size: "Regular", price: 350},
    ], 
    imgurl: "assets/images/MainDish/Beef Bulalo.jpg",
    category: "foods",
    all: "all",
    description: "Bulalo is a beef dish from the Philippines. It is a light colored soup that is made by cooking beef shanks and marrow bones until the collagen and fat has melted into the clear broth. Bulalo is native to the Southern Luzon region of the Philippines. Many references have evolved regarding its origin.",
    quantity: 1,
}, {
    id: 30,
    category: "Foods",
    itemName: "Pork Menudo",
    subCategory: "Main Dish",
    sizes: [
        {size: "Regular", price: 250},
    ], 
    imgurl: "assets/images/MainDish/Pork Menudo.jpg",
    category: "foods",
    all: "all",
    description: "A traditional stew from the Philippines made with pork and sliced liver in tomato sauce with carrots and potatoes. Unlike the Mexican dish of the same name, it does not use tripe or red chili sauce.",
    quantity: 1,
}, {
    id: 31,
    category: "Foods",
    itemName: "Pork Caldereta",
    subCategory: "Main Dish",
    sizes: [
        {size: "Regular", price: 250},
    ], 
    imgurl: "assets/images/MainDish/Pork Caldereta.png",
    category: "foods",
    all: "all",
    description: "Kaldereta or caldereta is a goat meat stew from the Philippines. Variations of the dish use beef, chicken, or pork. Commonly, the goat meat is stewed with vegetables and liver paste. Vegetables may include tomatoes, potatoes, olives, bell peppers, and hot peppers",
    quantity: 1,
}, {
    id: 32,
    category: "Foods",
    itemName: "Chicken Afritada",
    subCategory: "Main Dish",
    sizes: [
        {size: "Regular", price: 239},
    ], 
    imgurl: "assets/images/MainDish/Chicken Afritada.jpg",
    category: "foods",
    all: "all",
    description: "Afritada is a Philippine dish consisting of chicken, beef, or pork braised in tomato sauce with carrots, potatoes, and red and green bell peppers. It is served on white rice and is a common everyday Filipino meal. It can also be used to cook seafood.",
    quantity: 1,
}, {
    id: 33,
    category: "Foods",
    itemName: "Bicol Express",
    subCategory: "Main Dish",
    sizes: [
        {size: "Regular", price: 239},
    ], 
    imgurl: "assets/images/MainDish/Bicol Express.jpg",
    category: "foods",
    all: "all",
    description: "Bicol Express is a spicy Filipino stew made with bite-size pieces of pork simmered in coconut milk, shrimp paste, and chilies. Many variations exist; this one has sweet pineapple to balance the salty and spicy flavors.",
    quantity: 1,
}, {
    id: 35,
    category: "Foods",
    itemName: "Pork Steak",
    subCategory: "Main Dish",
    sizes: [
        {size: "Regular", price: 250},
    ], 
    imgurl: "assets/images/MainDish/Pork Steak.jpg",
    category: "foods",
    all: "all",
    description: "A steak is a thick cut of meat generally sliced across the muscle fibers, sometimes including a bone. It is normally grilled or fried. Steak can be diced, cooked in sauce, such as in steak and kidney pie, or minced and formed into patties, such as hamburgers.",
    quantity: 1,
}, {
    id: 36,
    category: "Foods",
    itemName: "Garlic Butter shrimp",
    subCategory: "Main Dish",
    sizes: [
        {size: "Regular", price: 300},
    ], 
    imgurl: "assets/images/MainDish/Garlic Butter shrimp.jpg",
    category: "foods",
    all: "all",
    description: "Garlic butter shrimp with sauce is topped over warm white rice. It can be eaten without any additional condiments because it is tasty by itself. I also like having this with toasted slices of French bread.",
    quantity: 1,
}, {
    id: 37,
    category: "Foods",
    itemName: "Pork Sisig",
    subCategory: "Main Dish",
    sizes: [
        {size: "Regular", price: 295},
    ], 
    imgurl: "assets/images/MainDish/Pork Sisig.jpg",
    category: "foods",
    all: "all",
    description: "A Filipino dish made from pork jowl and ears (maskara), pork belly, and chicken liver which is usually seasoned with calamansi, onions, and chili peppers. It originates from the Pampanga region in Luzon. Kapampangan sisig served on a hot plate.",
    quantity: 1,
}, {
    id: 1,
    category: "Foods",
    itemName: "Sinigang na Hipon",
    subCategory: "Main Dish",
    sizes: [
        {size: "Regular", price: 250},
    ], 
    imgurl: "assets/images/MainDish/Sinigang na Hipon.jpg",
    category: "foods",
    all: "all",
    description: "Sinigang na Hipon is a type of Filipino sour soup, wherein shrimp is used as the main ingredient. This dish also includes a variety of vegetables such as daikon radish, snake beans, okra, and eggplant. This dish is best served during cold weather. It is best enjoyed hot with a cup of white rice.",
    quantity: 1,
}, {
    id: 38,
    category: "Foods",
    itemName: "Sinigang na Baboy",
    subCategory: "Main Dish",
    sizes: [
        {size: "Regular", price: 250},
    ], 
    imgurl: "assets/images/MainDish/Sinigang na Baboy.jpg",
    category: "foods",
    all: "all",
    description: "Sinigang na Baboy is the ultimate comfort food! Made with pork ribs, vegetables, and tamarind-flavored broth, it’s hearty and delicious on its own or served with steamed rice.",
    quantity: 1,
}, {
    id: 39,
    category: "Foods",
    itemName: "Lechon Kawali",
    subCategory: "Main Dish",
    sizes: [
        {size: "Regular", price: 300},
    ], 
    imgurl: "assets/images/MainDish/LechonKawali.jpg",
    category: "foods",
    all: "all",
    description: "Lechon kawali, also known as lechon de carajay or litsong kawali in Tagalog, is a Filipino recipe consisting of pork belly slabs deep-fried in a pan or wok (kawali). It is seasoned beforehand, cooked then served in cubes.",
    quantity: 1,
}, {
    id: 40,
    category: "Foods",
    itemName: "Beef Kare-Kare",
    subCategory: "Main Dish",
    sizes: [
        {size: "Regular", price: 300},
    ], 
    imgurl: "assets/images/MainDish/Beef Kare-Kare.jpg",
    category: "foods",
    all: "all",
    description: "Kare-kare is a Philippine stew (kare derives from \"curry\") that features a thick savory peanut sauce. It is generally made from a base of stewed oxtail, beef tripe, pork hocks, calves' feet, pig's feet or trotters, various cuts of pork, beef stew meat, and occasionally offal.",
    quantity: 1,
}, {
    id: 41,
    category: "Foods",
    itemName: "Chicken Cordon Bleu",
    subCategory: "Main Dish",
    sizes: [
        {size: "Regular", price: 220},
    ], 
    imgurl: "assets/images/MainDish/Chicken Cordon Bleu.jpg",
    category: "foods",
    all: "all",
    description: "Chicken cordon bleu is a chicken breast pounded thin and filled with a piece of Swiss cheese and ham, then covered with breadcrumbs and baked in the oven or fried. It is extremely versatile, delicious accompanied by any steamed green vegetable, French fries, creamy mash potatoes or rice.",
    quantity: 1,
}, {
    id: 42,
    category: "Foods",
    itemName: "Fresh Green Beans",
    subCategory: "Side Dish",
    sizes: [
        {size: "Regular", price: 130},
    ], 
    imgurl: "assets/images/SideDish/FreshGreenBeans.jpg",
    category: "foods",
    all: "all",
    description: "Green beans are vegetables that grow on vines during the summer and fall months. They are also called string beans or snap beans. Yellow wax beans, purple bush beans and purple and beige heirloom varieties are included in the green bean family.",
    quantity: 1,
}, {
    id: 43,
    category: "Foods",
    itemName: "Sautéed Zucchini And Squash",
    subCategory: "Side Dish",
    sizes: [
        {size: "Regular", price: 150},
    ], 
    imgurl: "assets/images/SideDish/SautéedZucchiniAndSquash.jpg",
    category: "foods",
    all: "all",
    description: "A combination of fresh zucchini, yellow squash, sweet onions, and garlic, quickly sautéed together in butter for a delicious summer side dish.",
    quantity: 1,
}, {
    id: 44,
    category: "Foods",
    itemName: "Roasted Veggies",
    subCategory: "Side Dish",
    sizes: [
        {size: "Regular", price: 150},
    ], 
    imgurl: "assets/images/SideDish/RoastedVeggies.jpg",
    category: "foods",
    all: "all",
    description: "Roast veggies taste lightly crisp on the outside, and tender and caramelized on the inside. ",
    quantity: 1,
}, {
    id: 45,
    category: "Foods",
    itemName: "Roasted Broccoli With Sweet Chili Sauce",
    subCategory: "Side Dish",
    sizes: [
        {size: "Regular", price: 145},
    ], 
    imgurl: "assets/images/SideDish/RoastedBroccoliWithSweetChiliSauce.jpg",
    category: "foods",
    all: "all",
    description: "This addicting air fryer broccoli has charred, crispy edges and is tossed in a sweet, tangy sauce. The extra charred pieces are my favorite part! Even picky eaters will be going back for seconds. This makes an excellent accompaniment for fish or chicken, or served on top of rice.",
    quantity: 1,
}, {
    id: 46,
    category: "Foods",
    itemName: "Roasted Ratatouille",
    subCategory: "Side Dish",
    sizes: [
        {size: "Regular", price: 165},
    ], 
    imgurl: "assets/images/SideDish/RoastedRatatouille.jpg",
    category: "foods",
    all: "all",
    description: "Oven roasted ratatouille makes a delicious side dish for grilled or roasted meat, like Herb Roasted Pork Tenderloin, Garlic Butter Baked Cod, or Herb Roasted Chicken Breast. You could also serve this as part of a vegetarian meal by pairing it with something like a rich and creamy risotto or serving it on top of a bowl of polenta.",
    quantity: 1,
}, {
    id: 47,
    category: "Foods",
    itemName: "Pearl Couscous Salad",
    subCategory: "Side Dish",
    sizes: [
        {size: "Regular", price: 190},
    ], 
    imgurl: "assets/images/SideDish/PearlCouscousSalad.jpg",
    category: "foods",
    all: "all",
    description: "Pearl couscous is a type of pasta made from semolina so it tastes like tiny pasta pearls. If you take the extra step and sauté it with a bit of oil before boiling it, it will develop a sweet, almost nutty flavor that pairs perfectly with stews, braises, and grilled or roasted vegetables.",
    quantity: 1,
}, {
    id: 48,
    category: "Foods",
    itemName: "Mediterranean Quinoa Salad",
    subCategory: "Side Dish",
    sizes: [
        {size: "Regular", price: 200},
    ], 
    imgurl: "assets/images/SideDish/MediterraneanQuinoaSalad.jpg",
    category: "foods",
    all: "all",
    description: "It contains all nine essential amino acids that our bodies cannot make on their own. Quinoa is also naturally gluten-free and can be eaten safely if one has gluten intolerance such as celiac disease.",
    quantity: 1,
}, {
    id: 49,
    category: "Foods",
    itemName: "Chilaquiles",
    subCategory: "Side Dish",
    sizes: [
        {size: "Regular", price: 175},
    ], 
    imgurl: "assets/images/SideDish/Chilaquiles.jpg",
    category: "foods",
    all: "all",
    description: "A Mexican dish consisting of strips or pieces of corn tortillas that are fried, then sautéed with green or red salsa, and topped with cheese, crema (a sweet, thin cream sauce), and onion. Pulled chicken may also be added during the cooking process, and casserole versions of the dish are popular.",
    quantity: 1,
}, {
    id: 50,
    category: "Foods",
    itemName: "Crockpot Mac And Cheese",
    subCategory: "Side Dish",
    sizes: [
        {size: "Regular", price: 155},
    ], 
    imgurl: "assets/images/SideDish/Crockpot Mac And Cheese.jpg",
    category: "foods",
    all: "all",
    description: "A rich and creamy dish consisting of macaroni pasta mixed with a cheesy sauce. It's particularly popular in the United States.",
    quantity: 1,
}, {
    id: 51,
    category: "Foods",
    itemName: "Filet Mignon Nachos",
    subCategory: "Side Dish",
    sizes: [
        {size: "Regular", price: 198},
    ], 
    imgurl: "assets/images/SideDish/Filet Mignon Nachos.jpg",
    category: "foods",
    all: "all",
    description: "A dish of several individual tortilla chips topped with cheese, pickled jalapeño peppers, refried beans, etc., and baked or broiled.",
    quantity: 1,
}, {
    id: 52,
    category: "Foods",
    itemName: "Spicy Shrimp Nacho",
    subCategory: "Side Dish",
    sizes: [
        {size: "Regular", price: 255},
    ], 
    imgurl: "assets/images/SideDish/Spicy Shrimp Nacho.jpg",
    category: "foods",
    all: "all",
    description: "Spicy Shrimp Nachos, which feature tender shrimp on a bed of restaurant style tortilla chips, topped with melted cheese, chopped red onion and cilantro and drizzled with a spicy vinaigrette.",
    quantity: 1,
}, {
    id: 53,
    category: "Foods",
    itemName: "Surf And Turf Taco Combo",
    subCategory: "Side Dish",
    sizes: [
        {size: "Regular", price: 250},
    ], 
    imgurl: "assets/images/SideDish/Surf And Turf Taco Combo.jpg",
    category: "foods",
    all: "all",
    description: "Surf and Turf involves a combination meal with both seafood and red meat. The “surf” part refers to the seafood, and the “turf” part refers to animals that feed on grass (cows). The red meat is typically grilled while the seafood can be grilled, fried, baked or boiled.",
    quantity: 1,
}, {
    id: 54,
    category: "Foods",
    itemName: "Cheesy Enchiladas",
    subCategory: "Side Dish",
    sizes: [
        {size: "Regular", price: 190},
    ], 
    imgurl: "assets/images/SideDish/Cheesy Enchiladas.jpg",
    category: "foods",
    all: "all",
    description: "A Mexican dish that's made from tortillas wrapped around meat or cheese, and cooked in a spicy sauce. The earliest enchiladas were simply a plain tortilla served with chili sauce.",
    quantity: 1,
}, {
    id: 55,
    category: "Foods",
    itemName: "Banditto Burrito",
    subCategory: "Side Dish",
    sizes: [
        {size: "Regular", price: 123},
    ], 
    imgurl: "assets/images/SideDish/Banditto Burrito.jpeg",
    category: "foods",
    all: "all",
    description: "Pulled Pork with rice, sour cream, cheese, homemade salsa, and house slaw. Why not make it extra hot … for free. Available as a Burrito or Burrito Bowl (ingredients without the wrap).",
    quantity: 1,
}, {
    id: 56,
    category: "Foods",
    itemName: "Quesadilla",
    subCategory: "Side Dish",
    sizes: [
        {size: "Regular", price: 230},
    ], 
    imgurl: "assets/images/SideDish/Quesadilla.jpeg",
    category: "foods",
    all: "all",
    description: "A Mexican dish consisting of a tortilla that is filled primarily with cheese, and sometimes meats, spices, and other fillings, and then cooked on a griddle or stove.",
    quantity: 1,
}, {
    id: 57,
    category: "Foods",
    itemName: "Garlic Bread",
    subCategory: "Appetizers",
    sizes: [
        {size: "Regular", price: 245},
    ], 
    imgurl: "assets/images/AppetizerAndSoups/Garlic Bread.jpg",
    category: "foods",
    all: "all",
    description: "Garlic bread is toasted bread—usually French bread or baguette—topped with either butter or olive oil, garlic, herbs, and sometimes cheese. Garlic bread is derived from Italian bruschetta and is typically served alongside Italian foods like pasta, lasagna, or pizza.",
    quantity: 1,
}, {
    id: 58,
    category: "Foods",
    itemName: "Chicken Wings",
    subCategory: "Appetizers",
    sizes: [
        {size: "Small", price: 290},
        {size: "Medium", price: 745},
    ], 
    imgurl: "assets/images/AppetizerAndSoups/chicken_wing_regular.jpg",
    category: "foods",
    all: "all",
    description: "Chicken wings are white meat, even though they're juicier and have a more concentrated poultry flavor, like dark meat. Many people think of Buffalo wings when they think of this part of the chicken, and for good reason: they're extremely popular throughout the United States.",
    quantity: 1,
}, {
    id: 60,
    category: "Foods",
    itemName: "Beef Sliders",
    subCategory: "Appetizers",
    sizes: [
        {size: "Regular", price: 240},
        {size: "Large", price: 450},

    ], 
    imgurl: "assets/images/AppetizerAndSoups/SINGLE_Beef Sliders.jpg",
    category: "foods",
    all: "all",
    description: "The slider is not just a small burger – a slider is a small burger where the patty is cooked with onions and pickles. A true slider is made by cooking the onions, putting the patties on top and then flipping the entire thing and cooking further.",
    quantity: 1,
},{
    id: 62,
    category: "Foods",
    itemName: "Fried Zucchini",
    subCategory: "Appetizers",
    sizes: [
        {size: "Regular", price: 240},
    ], 
    imgurl: "assets/images/AppetizerAndSoups/Fried Zucchini.jpeg",
    category: "foods",
    all: "all",
    description: "Fried Zucchini is a delicious way to enjoy all of that summer zucchini from your yard…or your well-meaning neighbor or coworker. Zucchini is sliced into medallions, coated in a parmesan breadcrumb mixture and fried until crispy!",
    quantity: 1,
}, {
    id: 63,
    category: "Foods",
    itemName: "Onion Rings  ",
    subCategory: "Appetizers",
    sizes: [
        {size: "Regular", price: 220},
    ], 
    imgurl: "assets/images/AppetizerAndSoups/Onion Rings.jpg",
    category: "foods",
    all: "all",
    description: "An onion ring, also called a French fried onion ring, is a form of appetizer or side dish in British and American cuisine. They generally consist of a cross-sectional \"ring\" of onion dipped in batter or bread crumbs and then deep fried; a variant is made with onion paste.",
    quantity: 1,
}, {
    id: 64,
    category: "Foods",
    itemName: "Jumbo Shrimp Cocktail",
    subCategory: "Appetizers",
    sizes: [
        {size: "Regular", price: 220},
        {size: "Large", price: 745},
    ], 
    imgurl: "assets/images/AppetizerAndSoups/REGULAR_Jumbo Shrimp Cocktail.jpg",
    category: "foods",
    all: "all",
    description: "A shrimp cocktail consists of boiled and chilled shrimp that is often served up on the ice with cocktail sauce and garnished with lemon and leafy or parsley greens.",
    quantity: 1,
}, {
    id: 66,
    category: "Foods",
    itemName: "Mozzarella Sticks",
    subCategory: "Appetizers",
    sizes: [
        {size: "Regular", price: 349},
    ], 
    imgurl: "assets/images/AppetizerAndSoups/mozzarella_sticks_regular.jpg",
    category: "foods",
    all: "all",
    description: "Our favorite mozzarellas strike a perfect balance of milky, grassy, and floral notes with just a hint of tang. It's sort of like biting into a cool breeze on a warm spring day.",
    quantity: 1,
}, {
    id: 67,
    category: "Foods",
    itemName: "Tomato Soup",
    subCategory: "Soups",
    sizes: [
        {size: "Regular", price: 175},
    ], 
    imgurl: "assets/images/AppetizerAndSoups/CUP_Tomato Soup.jpg",
    category: "foods",
    all: "all",
    description: "Tomato soup is a soup with tomatoes as the primary ingredient. It can be served hot or cold, and may be made in a variety of ways. It may be smooth in texture, and there are also recipes that include chunks of tomato, cream, chicken or vegetable stock, vermicelli, chunks of other vegetables and meatballs.",
    quantity: 1,
}, {
    id: 68,
    category: "Foods",
    itemName: "Tomato Soup",
    subCategory: "Soups",
    sizes: [
        {size: "Regular", price: 169},
    ], 
    imgurl: "assets/images/AppetizerAndSoups/BOWL_Tomato Soup.png",
    category: "foods",
    all: "all",
    description: "Tomato soup is a soup with tomatoes as the primary ingredient. It can be served hot or cold, and may be made in a variety of ways. It may be smooth in texture, and there are also recipes that include chunks of tomato, cream, chicken or vegetable stock, vermicelli, chunks of other vegetables and meatballs.",
    quantity: 1,
}, {
    id: 69,
    category: "Foods",
    itemName: "Chicken Noodle Soup",
    subCategory: "Soups",
    sizes: [
        {size: "Regular", price: 224},
    ], 
    imgurl: "assets/images/AppetizerAndSoups/CUP_Chicken Noodle Soup.jpg",
    category: "foods",
    all: "all",
    description: "Chicken Noodle Soup is simply made with egg noodles and bits of chicken cooked in a chicken stock. Often the soup will also contain several types of vegetables which may include carrots, onions and celery.",
    quantity: 1,
}, {
    id: 70,
    category: "Foods",
    itemName: "Chicken Noodle Soup",
    subCategory: "Soups",
    sizes: [
        {size: "Regular", price: 314},
    ], 
    imgurl: "assets/images/AppetizerAndSoups/BOWL_Chicken Noodle Soup.jpg",
    category: "foods",
    all: "all",
    description: "Chicken Noodle Soup is simply made with egg noodles and bits of chicken cooked in a chicken stock. Often the soup will also contain several types of vegetables which may include carrots, onions and celery.",
    quantity: 1,
}, {
    id: 71,
    category: "Foods",
    itemName: "Garden Salad",
    subCategory: "Salad",
    sizes: [
        {size: "Regular", price: 290},
    ], 
    imgurl: "assets/images/AppetizerAndSoups/Garden Salad.jpg",
    category: "foods",
    all: "all",
    description: "Mixed greens, hard boiled egg, tomato, onion, cucumber, carrots, black olives and pepperoncini, choice of dressing",
    quantity: 1,
}, {
    id: 72,
    category: "Foods",
    itemName: "Spaghetti with Meatballs",
    subCategory: "Pasta",
    sizes: [
        {size: "Regular", price: 349},
    ], 
    imgurl: "assets/images/PastaandPizza/Spaghetti with Meatballs.jpg",
    category: "foods",
    all: "all",
    description: "Italian inspired pasta top by meatballs and diced chicken",
    quantity: 1,
}, {
    id: 73,
    category: "Foods",
    itemName: "Classic Filipino Style Spaghetti",
    subCategory: "Pasta",
    sizes: [
        {size: "Regular", price: 229},
    ], 
    imgurl: "assets/images/PastaandPizza/Classic Filipino Style Spaghetti.jpg",
    category: "foods",
    all: "all",
    description: "Cheesy pasta with tomato sauce sweetened with brown sugar ",
    quantity: 1,
}, {
    id: 74,
    category: "Foods",
    itemName: "Spaghetti with Marinara Sauce",
    subCategory: "Pasta",
    sizes: [
        {size: "Regular", price: 329},
    ], 
    imgurl: "assets/images/PastaandPizza/Spaghetti with Marinara Sauce.jpg",
    category: "foods",
    all: "all",
    description: "Classic sphagetti with homemade marinara sauce",
    quantity: 1,
}, {
    id: 75,
    category: "Foods",
    itemName: "Creamy Shrimp Pasta",
    subCategory: "Pasta",
    sizes: [
        {size: "Regular", price: 349},
    ], 
    imgurl: "assets/images/PastaandPizza/Creamy Shrimp Pasta.jpg",
    category: "foods",
    all: "all",
    description: "Creamy pasta with fresh shrimp, black olives and mushrooms",
    quantity: 1,
}, {
    id: 76,
    category: "Foods",
    itemName: "Triple Cheese Pasta",
    subCategory: "Pasta",
    sizes: [
        {size: "Regular", price: 349},
    ], 
    imgurl: "assets/images/PastaandPizza/Triple Cheese Pasta.jpg",
    category: "foods",
    all: "all",
    description: "Cheese past loaded with 3 diferrent cheese and cheese sauce",
    quantity: 1,
}, {
    id: 77,
    category: "Foods",
    itemName: "Carbonara",
    subCategory: "Pasta",
    sizes: [
        {size: "Regular", price: 249},
    ], 
    imgurl: "assets/images/PastaandPizza/Carbonara.jpg",
    category: "foods",
    all: "all",
    description: "Filipino style carbonara with smoke ham, mushrooms",
    quantity: 1,
}, {
    id: 78,
    category: "Foods",
    itemName: "Parmesan Cheese Pasta",
    sizes: [
        {size: "Regular", price: 329},
    ], 
    imgurl: "assets/images/PastaandPizza/Parmesan Cheese Pasta.jpg",
    category: "foods",
    all: "all",
    description: "Parmesan cheese sauce with fresh spinach",
    quantity: 1,
}, {
    id: 79,
    category: "Foods",
    itemName: "Veggie Pasta",
    subCategory: "Pasta",
    sizes: [
        {size: "Regular", price: 315},
    ], 
    imgurl: "assets/images/PastaandPizza/Veggie Pasta.jpg",
    category: "foods",
    all: "all",
    description: "Spaghetti with fresh tomatoes, mushrooms, onions, bell peppers, fresh garlic and olive oil.",
    quantity: 1,
}, {
    id: 80,
    category: "Foods",
    itemName: "Veggie Supreme Pizza",
    subCategory: "Pizza",
    sizes: [
        {size: "Regular", price: 349},
    ], 
    imgurl: "assets/images/PastaandPizza/Veggie Supreme Pizza.jpg",
    category: "foods",
    all: "all",
    description: "Creamy garlic sauce, mushrooms, tomatoes, red onions, fresh spinach & mozzarella",
    quantity: 1,
}, {
    id: 81,
    category: "Foods",
    itemName: "BBQ Chicken Pizza",
    subCategory: "Pizza",
    sizes: [
        {size: "Regular", price: 375},
    ], 
    imgurl: "assets/images/PastaandPizza/BBQ Chicken Pizza.jpg",
    category: "foods",
    all: "all",
    description: "Chicken, BBQ sauce, red onions, cilantro & mozzarella cheese",
    quantity: 1,
}, {
    id: 82,
    category: "Foods",
    itemName: "Meat Lovers",
    subCategory: "Pizza",
    sizes: [
        {size: "Regular", price: 399},
    ], 
    imgurl: "assets/images/PastaandPizza/Meat Lovers.jpg",
    category: "foods",
    all: "all",
    description: "Pepperoni, sausage, meatball, ham, bacon, tomato sauce and mozzarella cheese",
    quantity: 1,
}, {
    id: 83,
    category: "Foods",
    itemName: "Extra Cheesy Pizza",
    subCategory: "Pizza",
    sizes: [
        {size: "Regular", price: 349},
    ], 
    imgurl: "assets/images/PastaandPizza/Extra Cheesy Pizza.jpeg",
    category: "foods",
    all: "all",
    description: "Loaded with differentr types of cheese, Cheese inside the crust",
    quantity: 1,
}, {
    id: 84,
    category: "Foods",
    itemName: "Classic Pepperoni Pizza",
    subCategory: "Pizza",
    sizes: [
        {size: "Regular", price: 375},
    ], 
    imgurl: "assets/images/PastaandPizza/Classic Pepperoni Pizza.jpg",
    category: "foods",
    all: "all",
    description: "Crispy pepperoni slice, mozzarella cheese, mushrooms with blue cheese dressings",
    quantity: 1,
}, {
    id: 85,
    category: "Foods",
    itemName: "Hawaiian Pizza",
    subCategory: "Pizza",
    sizes: [
        {size: "Regular", price: 375},
    ], 
    imgurl: "assets/images/PastaandPizza/Hawaiian Pizza.jpg",
    category: "foods",
    all: "all",
    description: "Smoked bacon, ham, pineapple, and extra cheese",
    quantity: 1,
}, {
    id: 86,
    category: "Foods",
    itemName: "Chicken & Spinach Pizza",
    subCategory: "Pizza",
    sizes: [
        {size: "Regular", price: 399},
    ], 
    imgurl: "assets/images/PastaandPizza/Chicken _ Spinach Pizza.jpg",
    category: "foods",
    all: "all",
    description: "Diced chicken with homemade buffalo sauce with fresh spinach on top",
    quantity: 1,
},{
    id: 87,
    category: "Desserts",
    itemName: "Mango Float",
    subCategory: "Cold",
    sizes: [
        {size: "Regular", price: 100},
    ], 
    imgurl: "assets/images/Dessert/REGULAR_Mango Float.jpg",
    category: "desserts",
    all: "all",
    description: "3 layered graham biscuit with the sweetness of condensed milk with the creaminess of all purpose cream, filled with mango slices in the bottom, middle and a toppings of it with mashed graham biscuit.",
    quantity: 1,
}, {
    id: 88,
    category: "Desserts",
    itemName: "Yema Cake",
    subCategory: "Cake",
    sizes: [
        {size: "Half", price: 145},
        {size: "Whole", price: 290},
    ], 
    imgurl: "assets/images/Dessert/SLICE_Yema Cake.jpg",
    category: "desserts",
    all: "all",
    description: "A local sponge cake with custard frosting  with soft shredded cheese. The sweet and deliciousness that you've never tasted before.",
    quantity: 1,
}, {
    id: 90,
    category: "Desserts",
    itemName: "Brazo De Mercedes",
    subCategory: "Cake",
    sizes: [
        {size: "Half", price: 115},
        {size: "Whole", price: 230},
    ],
    imgurl: "assets/images/Dessert/SLICE_Brazo De Mercedes.jpg",
    category: "desserts",
    all: "all",
    description: "A rolled cake made from thick sheet of soft meringue with custard feeling.",
    quantity: 1,
}, {
    id: 92,
    category: "Desserts",
    itemName: "Bibingka",
    subCategory: "Hot",
    sizes: [
        {size: "Regular", price: 65},
    ],
    imgurl: "assets/images/Dessert/Bibingka.jpg",
    category: "desserts",
    all: "all",
    description: "Made of sticky rice with the taste of brown sugar, covered with banana leaves.",
    quantity: 1,
}, {
    id: 93,
    category: "Desserts",
    itemName: "Leche Flan",
    subCategory: "Custard",
    sizes: [
        {size: "Regular", price: 100},
    ],
    imgurl: "assets/images/Dessert/Leche Flan.jpg",
    category: "desserts",
    all: "all",
    description: "A soft dessert made up from eggs and milk with soft caramel on top. ",
    quantity: 1,
}, {
    id: 94,
    category: "Desserts",
    itemName: "Buko Salad",
    subCategory: "Cold",
    sizes: [
        {size: "Regular", price: 100},
    ],
    imgurl: "assets/images/Dessert/Buko Salad.jpg",
    category: "desserts",
    all: "all",
    description: "Made of shredded sweet young coconut with milk and fruit cocktail, nata de coco and palm fruit.",
    quantity: 1,
}, {
    id: 95,
    category: "Desserts",
    itemName: "Coffee Jelly",
    subCategory: "Cold",
    sizes: [
        {size: "Regular", price: 100},
    ],
    imgurl: "assets/images/Dessert/Coffee Jelly.jpg",
    category: "desserts",
    all: "all",
    description: "A coffee flavored gelatin and served with evaporated milk.",
    quantity: 1,
}, {
    id: 96,
    category: "Desserts",
    itemName: "Buko Pie",
    subCategory: "Cake",
    sizes: [
        {size: "Half slice", price: 95},
        {size: "Whole", price: 190},
    ],
    imgurl: "assets/images/Dessert/SLICE_Buko Pie.jpg",
    category: "desserts",
    all: "all",
    description: "This pie made of tender young coconut meat in a creamy filling and a crisp and buttery pastry crust",
    quantity: 1,
},{
    id: 98,
    category: "Desserts",
    itemName: "Halo - Halo",
    subCategory: "Shaved ice",
    sizes: [
        {size: "Small", price: 50},
        {size: "Medium", price: 65},
        {size: "Large", price: 70},

    ],
    imgurl: "assets/images/Dessert/SMALL_Halo - Halo.jpg",
    category: "desserts",
    all: "all",
    description: "A shaved ice dessert with sweetened beans, jellies and milk. Topped with leche flan, ube halaya and ice cream.",
    quantity: 1,
}, {
    id: 101,
    category: "Desserts",
    itemName: "Maja Blanca",
    subCategory: "Cake",
    sizes: [
        {size: "Half", price: 75},
        {size: "Whole", price: 150},

    ],
    imgurl: "assets/images/Dessert/HALF_Maja Blanca.jpg",
    category: "desserts",
    all: "all",
    description: "A creamy cococnut pudding with corn kernels.",
    quantity: 1,
},{
    id: 103,
    category: "Desserts",
    itemName: "Gulaman",
    subCategory: "Cold",
    sizes: [
        {size: "Regular", price: 30},
    ],
    imgurl: "assets/images/Dessert/Gulaman.jpeg",
    category: "desserts",
    all: "all",
    description: "A jelly like dessert partnered with condensed milk or evaporated milk.",
    quantity: 1,
}, {
    id: 104,
    category: "Desserts",
    itemName: "Polvoron",
    subCategory: "Shortbread",
    sizes: [
        {size: "Regular", price: 50},
    ],
    imgurl: "assets/images/Dessert/Polvoron.jpg",
    category: "desserts",
    all: "all",
    description: "A shortbread dessert made with toasted flour, powdered milk and butter.",
    quantity: 1,
}, {
    id: 105,
    category: "Desserts",
    itemName: "Churos",
    subCategory: "Fried",
    sizes: [
        {size: "Regular", price: 100},
    ],
    imgurl: "assets/images/Dessert/Churos.jpg",
    category: "desserts",
    all: "all",
    description: "A deep fried dough pastry dusted with cinnamon sugar and dip into sweet chocolate.",
    quantity: 1,
}, {
    id: 107,
    category: "Desserts",
    itemName: "Mais Con Hielo",
    subCategory: "Shaved ice",
    sizes: [
        {size: "Small", price: 70},
        {size: "Medium", price: 80},
        {size: "Large", price: 90},
    ],
    imgurl: "assets/images/Dessert/REGULAR_Mais Con Hielo.jpg",
    category: "desserts",
    all: "all",
    description: "A layered dessert consists of sweet corn, sweetened shaved ice and milk.",
    quantity: 1,
},{
    id: 109,
    category: "Desserts",
    itemName: "Saging con Hielo",
    subCategory: "Shaved ice",
    sizes: [
        {size: "Small", price: 55},
        {size: "Medium", price: 60},
        {size: "Large", price: 65},
    ],
    imgurl: "assets/images/Dessert/SMALL_Saging Con Hielo.jpg",
    category: "desserts",
    all: "all",
    description: "A shaved ice dessert with sweetened banana topped with shaved ice with sweetened banana sauce.",
    quantity: 1,
}];
